enum CpdType { course, reading, audit, teaching, other }

/// Auto-tags generated by AI for CPD entries
class CpdAutoTags {
  final String suggestedType;
  final List<int> domains;      // GMC domain numbers [1,2,3,4]
  final String impact;           // Description of learning impact
  
  CpdAutoTags({
    required this.suggestedType,
    required this.domains,
    required this.impact,
  });
  
  Map<String, dynamic> toJson() => {
    'type': suggestedType,
    'domains': domains,
    'impact': impact,
  };
  
  static CpdAutoTags fromJson(Map<String, dynamic> json) => CpdAutoTags(
    suggestedType: json['type'] as String? ?? '',
    domains: json['domains'] != null
      ? (json['domains'] as List).cast<int>()
      : [],
    impact: json['impact'] as String? ?? '',
  );
}

class CpdEntry {
  final String id;
  final CpdType type;
  final String title;
  final double hours;
  final DateTime date;
  final String? notes;
  final List<String> linkedReflectionIds;
  
  // AI auto-tagging
  final CpdAutoTags? autoTags;

  CpdEntry({
    required this.id,
    required this.type,
    required this.title,
    required this.hours,
    required this.date,
    this.notes,
    required this.linkedReflectionIds,
    this.autoTags,
  });

  CpdEntry copyWith({
    CpdType? type,
    String? title,
    double? hours,
    DateTime? date,
    String? notes,
    List<String>? linkedReflectionIds,
    CpdAutoTags? autoTags,
  }) => CpdEntry(
    id: id,
    type: type ?? this.type,
    title: title ?? this.title,
    hours: hours ?? this.hours,
    date: date ?? this.date,
    notes: notes ?? this.notes,
    linkedReflectionIds: linkedReflectionIds ?? this.linkedReflectionIds,
    autoTags: autoTags ?? this.autoTags,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type.name,
    'title': title,
    'hours': hours,
    'date': date.toIso8601String(),
    'notes': notes,
    'linkedReflectionIds': linkedReflectionIds,
    if (autoTags != null) 'autoTags': autoTags!.toJson(),
  };

  static CpdEntry fromJson(Map<String, dynamic> j) => CpdEntry(
    id: j['id'] as String,
    type: CpdType.values.byName(j['type'] as String),
    title: j['title'] as String,
    hours: (j['hours'] as num).toDouble(),
    date: DateTime.parse(j['date'] as String),
    notes: j['notes'] as String?,
    linkedReflectionIds: (j['linkedReflectionIds'] as List).cast<String>(),
    autoTags: j['autoTags'] != null
      ? CpdAutoTags.fromJson(j['autoTags'] as Map<String, dynamic>)
      : null,
  );
  
  /// Get GMC domains from auto-tags or return empty list
  List<int> get domains => autoTags?.domains ?? [];
  
  /// Check if entry has been auto-tagged
  bool get hasAutoTags => autoTags != null;
}
