// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa361ofmeJ1BPz2-N_qCrnwSBHMuX-hVI',
    appId: '1:1083790628363:web:382a41969e9346e8c4590e',
    messagingSenderId: '1083790628363',
    projectId: 'metanoia-a3035',
    authDomain: 'metanoia-a3035.firebaseapp.com',
    storageBucket: 'metanoia-a3035.firebasestorage.app',
    measurementId: 'G-PLVLE06WR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbd4KuGL9pHt1ERBMQvgq0fyULnCrgkw',
    appId: '1:1083790628363:android:e42d61f21952047bc4590e',
    messagingSenderId: '1083790628363',
    projectId: 'metanoia-a3035',
    storageBucket: 'metanoia-a3035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOvTUjIonJF-VksYowpX52IaC4KukvCIw',
    appId: '1:1083790628363:ios:3bea9c1aba4b9b3ec4590e',
    messagingSenderId: '1083790628363',
    projectId: 'metanoia-a3035',
    storageBucket: 'metanoia-a3035.firebasestorage.app',
    iosBundleId: 'com.example.metanoiaFlutter',
  );

}