// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhR0ywnmOOqiZ2cmfxQe0uBFsAVlTY24',
    appId: '1:639783242016:web:e05fde7cf3870a8804af45',
    messagingSenderId: '639783242016',
    projectId: 'mindclon-dev',
    authDomain: 'mindclon-dev.firebaseapp.com',
    storageBucket: 'mindclon-dev.firebasestorage.app',
    measurementId: 'G-CTEGND8XCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSgMoGlXKNPkXKlIory_ddfz3yX8zHJY',
    appId: '1:639783242016:android:357ef9792b9c57a104af45',
    messagingSenderId: '639783242016',
    projectId: 'mindclon-dev',
    storageBucket: 'mindclon-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACeNqSepBVHkTPYWLrzkEJvdeFIUAlO90',
    appId: '1:639783242016:ios:8e439e0e4fac797504af45',
    messagingSenderId: '639783242016',
    projectId: 'mindclon-dev',
    storageBucket: 'mindclon-dev.firebasestorage.app',
    iosBundleId: 'com.metanoia.flutter.v2',
  );

}